export const matches = [
    { id: 1, title: "vsFEYENOORD", coverImage: "/images/vsFEYENOORD.png", details: "" },
    { id: 2, title: "vsAJAX", coverImage: "/images/vsAJAX.png", details: "" },
    { id: 3, title: "vsAZ", coverImage: "/images/vsAZ.png", details: "" },
    { id: 4, title: "vsVITESSE", coverImage: "/images/vsVITESSE.png", details: "" },
    { id: 5, title: "vsSPARTAROTTERDAM", coverImage: "/images/vsSPARTAROTTERDAM.png", details: "" },
    { id: 6, title: "vsALMERECITYFC", coverImage: "/images/vsALMERECITYFC.png", details: "" },
    { id: 7, title: "vsFCGRONINGEN", coverImage: "/images/vsFCGRONINGEN.png", details: "" },
    { id: 8, title: "vsCAMBUUR", coverImage: "/images/vsCAMBUUR.png", details: "" },
    { id: 9, title: "vsPSV", coverImage: "/images/vsPSV.png", details: "" },
    { id: 10, title: "vsEXCELSIOR", coverImage: "/images/vsEXCELSIOR.png", details: "" },
    { id: 11, title: "vsADODENHAAG", coverImage: "/images/vsADODENHAAG.png", details: "" },
    { id: 12, title: "vsUNKNOWN", coverImage: "/images/vsUNKNOWN.png", details: "" },
    { id: 13, title: "vsNAC", coverImage: "/images/vsNAC.png", details: "" },
    { id: 14, title: "vsTWENTE", coverImage: "/images/vsTWENTE.png", details: "" },
    { id: 15, title: "vsHEERENVEEN", coverImage: "/images/vsHEERENVEEN.png", details: "" },
    { id: 16, title: "vsFORTUNASITTARD", coverImage: "/images/vsFORTUNASITTARD.png", details: "" },
    { id: 17, title: "vsNEC", coverImage: "/images/vsNEC.png", details: "" },
    { id: 18, title: "vsUTRECHT", coverImage: "/images/vsUTRECHT.png", details: "" },
  ];